aws_iam_role = "inventory_iam_role"
aws_iam_policy = "inventory_iam_policy"
aws_lambda_function = "inventory_lambda_function_name"
aws_lambda_function_handler = "hello.lambda_handler"
aws_region = "eu-west-2"
aws_access_key = "AKIA4H4ZNMOLO34UY6CW"
aws_secret_key = "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"